CLASSES_NAME : ["Aortic enlargement", "Cardiomegaly", "ILD", "Infiltration", "Nodule/Mass"]
NUM_CLASSES : 5
COLOR : [[59, 238, 119], [206, 221, 133], [0, 0, 255], [211, 176, 166], [102, 65, 77]]
MODEL : "COCO-Detection/retinanet_R_101_FPN_3x.yaml"
TRANSFER_LEARNING : "best_model_map50.pth"
NAME_REGISTER : "chestxray_"
RANDOM_FLIP : "none"
OUTPUT_DIR : "app/models"
SCORE_THR_VAL : 0.05
SCORE_THR : 0.5
NMS_THR_VAL : 0.5
NMS_THR : 0.5
ROI_HEADS_IOU_THRESHOLDS : 0.5
RETINANET_IOU_THRESHOLDS : [0.4, 0.5]
NUM_WORKERS : 4
DEVICE: "cpu"
IMS_PER_BATCH : 1
BATCH_SIZE_PER_IMAGE : 512
CHECK_TRAIN: True
CHECK_VAL : False